### ISSUE TITLE
Get Kopernicus (1.8)

### ISSUE THREAD

**Issue by AndresHdzArv** [linuxgurugamer/New_Horizons#6]
I want to test this on 1.8, but how do I get that Kopernicus build?

**Comment by linuxgurugamer** [comment]
You don't.  It's not released to the public yet, still in a testing mode
If you able, you could download and compile it yourself, but I don't recommend it.
Besides, NH is causingKSP 1.8.1 to become unresponsive at the main menu, so I don't recommend it.  It does work nicely in 1.7.3
